### ISSUE TITLE
Can't loading 

### ISSUE THREAD

**Issue by IFedor-F** [agnor99/arrow-sprites#1]
Hi, the mod cannot load
I used [Fabric - 1.0.0](https://modrinth.com/mod/sprite-arrows/version/lBMrP5Mb) from modrinth
Minecraft 1.19.4
Fabric Loader 0.14.19
https://mclo.gs/214nmwl
- Mods:
    - architectury-8.1.80-fabric
    - fabric-api-0.80.0+1.19.4
    - spritearrows-fabric-1.0.0

**Comment by agnor99** [comment]
Thanks for telling me, it was a typo in the fabric.mod.json file that somehow got in there between creation and publishing of the mod. idk how it happened, but I'll upload a fixed version asap.

**Comment by agnor99** [comment]
Fixed, you can get version 1.0.1 on modrinth

**Comment by IFedor-F** [comment]
Thanks!
