### ISSUE TITLE
[Compatibility] Backport Request

### ISSUE THREAD

**Issue by PotionSeeker** [agnor99/arrow-sprites#2]
I was looking at some of the code and I was wondering if it would be possible to backport this mod to other versions (1.19.2, 1.18.2) if it's not too much trouble?

**Comment by agnor99** [comment]
I've create and published a 1.19.2 version for forge and fabric, I'm not sure when I'll be able to backport it to 1.18.2 and maybe 1.16.5

**Comment by agnor99** [comment]
I'll keep this issue open until those versions are available too

**Comment by PotionSeeker** [comment]
Cool man! Thanks for that!

**Comment by justliliandev** [comment]
backport to 1.18.2 is done, 1.16.5 is probably not happening for the forseeable future
