### ISSUE TITLE
Incompatibility Issues

### ISSUE THREAD

**Issue by PotionSeeker** [agnor99/arrow-sprites#3]
**Game Version:**
Forge - 1.19.2
Forge Version - 43.2.11

**Initial Error Condition:**
- Large scale modpack (100+ Mods)

**Separate Tested Mods:**
- Mimic / GeckoLib
- Fancy Menu / Konkrete
- Yung's API
- Farmer's Delight

**Explanation:**
I hate to be a bother, but after testing this mod under a number of different conditions, I've found that there is a strange issue that causes Arrow Sprites to be incompatible with certain mods, but only under certain conditions.

Testing Arrow Sprites with Mimic and GeckoLib in an isolated environment seemingly showed that they were perfectly compatible, but when I increase the amount of mods that are being tested, the game eventually reaches a point where it crashes. The weird part is that no matter which mod was added last, the only mod that seems to stop the crashing is if either Arrow Sprites or the "incompatible" mod is removed.

For Example:
1. Arrow Sprites is installed - no issue
2. Mimic and GeckoLib are installed - still no issue 
3. 15 other mods are installed - game crashes
4. Attempting to remove any of those 15 other mods yields no results
5. Remove Mimic - game doesn't crash

I have tested this same scenario for Fancy Menu / Konkrete, Yung's API, and Farmer's Delight and have the same results: When in isolation they work together; when in a larger modpack, there is an issue. There are a few other mods that may be incompatible with Arrow Sprites, but these are the ones I've tested and noted this strange interaction.

**Crash Logs:**
[crash-2023-05-19_06.44.27-fml.txt](https://github.com/agnor99/arrow-sprites/files/11513794/crash-2023-05-19_06.44.27-fml.txt)

**Comment by agnor99** [comment]
uhh thanks, this is somewhat of a soft incompatability, because this can only happen if I and someone else did something wrong (Mimic also has this problem, I'll report it to them as well) and I'll try to update the mod soon

**Comment by PotionSeeker** [comment]
The newest update (Arrow Sprites 1.0.2) fixed the issue with Mimic, Farmer's Delight and Yung's API, etc. but there are now  errors for mods such as "Iron's Spells 'n Spellbooks" "Dungeons Mobs" and "What Are You Voting For". 

It might not be something you can fix on your end, but I thought I'd let you know. 

They all seem to have the same issue with the EntityRenderer; they have the same description and the "detailed walkthrough of the error, its code path and all known details" all report the same thing: 
[Error Snippet.txt](https://github.com/agnor99/arrow-sprites/files/11516687/Error.Snippet.txt)

Iron's Spells 'n Spellbooks:
- [crash-2023-05-19_12.48.05-client.txt](https://github.com/agnor99/arrow-sprites/files/11516709/crash-2023-05-19_12.48.05-client.txt)

Dungeons Mobs:
- [crash-2023-05-19_12.41.30-client.txt](https://github.com/agnor99/arrow-sprites/files/11516711/crash-2023-05-19_12.41.30-client.txt)

What Are You Voting For:
- [crash-2023-05-19_12.37.48-client.txt](https://github.com/agnor99/arrow-sprites/files/11516712/crash-2023-05-19_12.37.48-client.txt)

This is still kind of related to the original incompatibility issue so I thought I should just add this here.

**Comment by agnor99** [comment]
This is a different error caused by those mods using a forge feature wrong (atleast in one case, the others are closed source, so no way to check that). I may fix that on my side, but no guarantees that I'll do that anytime soon

**Comment by PotionSeeker** [comment]
That's a shame. Well, if you can fix it that would be great, but don't worry yourself too much about it.
