### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by wiktormalyska** [agnor99/arrow-sprites#4]
with these mods
https://modrinth.com/mod/entity-model-features
https://modrinth.com/mod/entitytexturefeatures
`---- Minecraft Crash Report ----
// Oops.

Time: 2023-06-28 12:55:03
Description: mouseClicked event handler

java.lang.NullPointerException: Cannot read field "field_3761" because "this.serverInfo" is null
	at net.minecraft.class_442.mdc4e683$continue$lambda$drawMenuButton$2$6(class_442.java:4590)
	at net.minecraft.class_4185.method_25306(class_4185.java:94)
	at net.minecraft.class_4264.method_25348(class_4264.java:56)
	at net.minecraft.class_339.method_25402(class_339.java:189)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_442.method_25402(class_442.java:299)
	at net.minecraft.class_312.method_1611(class_312.java:98)
	at net.minecraft.class_437.method_25412(class_437.java:409)
	at net.minecraft.class_312.method_1601(class_312.java:98)
	at net.minecraft.class_312.method_22686(class_312.java:169)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:169)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:237)
	at net.minecraft.class_310.method_1523(class_310.java:1244)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_442.mdc4e683$continue$lambda$drawMenuButton$2$6(class_442.java:4590)
	at net.minecraft.class_4185.method_25306(class_4185.java:94)
	at net.minecraft.class_4264.method_25348(class_4264.java:56)
	at net.minecraft.class_339.method_25402(class_339.java:189)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_442.method_25402(class_442.java:299)
	at net.minecraft.class_312.method_1611(class_312.java:98)
	at net.minecraft.class_437.method_25412(class_437.java:409)
	at net.minecraft.class_312.method_1601(class_312.java:98)
	at net.minecraft.class_312.method_22686(class_312.java:169)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:169)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_442
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:409)
	at net.minecraft.class_312.method_1601(class_312.java:98)
	at net.minecraft.class_312.method_22686(class_312.java:169)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:169)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:237)
	at net.minecraft.class_310.method_1523(class_310.java:1244)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 2
	Reload reason: manual
	Finished: Yes
	Packs: vanilla, fabric, file/Twemojis in MInecraft 1.2.1.zip, minecraft:supporteatinganimation, file/better_flame_particles-v1.0-mc1.20-resourcepack.zip, file/enchant icons 1.20 v1.3.zip, file/corality-1-0-2.zip, file/falling-sakura-1-1-0.zip, file/repottery-v1-3-1.zip, file/EBE_1.20.x_v1.1.zip, continuity:default, minecraft:highlight_extended, translucent-glass:translucent-glass, itemswapper:default, file/Default-Dark-Mode-1.20-2023.6.0.zip, file/Fabulous+Foliage.zip
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2413)
	at net.minecraft.class_310.method_1514(class_310.java:821)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.20
	Minecraft Version ID: 1.20
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 664666424 bytes (633 MiB) / 2415919104 bytes (2304 MiB) up to 10737418240 bytes (10240 MiB)
	CPUs: 24
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 9 3900XT 12-Core Processor           
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.80
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 24
	Graphics card #0 name: NVIDIA GeForce GTX 1080 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1b06
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3179
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 42933.35
	Virtual memory used (MB): 24015.15
	Swap memory total (MB): 10240.00
	Swap memory used (MB): 101.34
	JVM Flags: 10 total; -Xmx10240M -XX:MetaspaceSize=256M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M
	Fabric Mods: 
		advancementscreenshot: Advancement Screenshot 4.2
		ambientsounds: AmbientSounds 5.2.20
		architectury: Architectury 9.0.8
		authme: Auth Me 7.0.1+1.20
			fabric-api-base: Fabric API Base 0.4.29+b04edc7a27
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.20+b3afc78b27
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.7+f7923f6d27
		axolotlbuckets: Axolotl Buckets 1.2.0
		barista: FPS Monitor 1.20-1.1.2-Fabric
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da27
		bee_info: More Bee info  1.1.2
		better_resource_pack_sorting: Better Resource Pack Sorting 1.0.0
		betteranimationscollection: Better Animations Collection 7.0.0
		betterarmorswap: BetterArmorSwap 0.1.0
		bettercommandblockui: BetterCommandBlockUI 0.4.2
		betterf3: BetterF3 7.0.0
		biomecreeper: Biome Creeper 1.2-BETA+1.20
		biomemoss: Biome Moss 1.1.0
		biomesniffer: Biome Sniffer 1.2-BETA+1.20
		blur: Blur (Fabric) 3.1.0
			midnightlib: MidnightLib 1.4.1
			satin: Satin 1.13.0
		borderlessmining: Borderless Mining 1.1.8+1.20.1
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.10.88
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.10.88
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.2.0+alpha.10.88
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.10.88
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.10.88
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.10.88
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.10.88
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.10.88
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.10.88
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.10.88
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.10.88
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.10.88
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.10.88
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.10.88
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.10.88
			c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.2.0+alpha.10.88
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.10.88
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.10.88
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.10.88
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.10.88
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.10.88
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			com_ibm_async_asyncutil: asyncutil 0.1.0
			net_objecthunter_exp4j: exp4j 0.4.8
			org_threadly_threadly: threadly 7.0
		cat_jam: cat_jam 1.1.1
		cavedust: Cave Dust 1.4.1
			kirin: Kirin UI 1.15.0
		chat_heads: Chat Heads 0.10.16
		chatsigninghider: Chat Signing Hider 1.20-1.0.0
		chatwalk: Chat Walk 1.0.2
		clickthrough: ClickThrough 1.20.1-fabric0.83.0-0.41
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
			gbfabrictools: GBfabrictools 1.3.4+1.19.3
		cloth-config: Cloth Config v11 11.0.99
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 6.62
		continue: Continue 1.1.1+1.20
		continuity: Continuity 3.0.0-beta.2+1.20
		controlling: Controlling For Fabric 12.0.2
		cr3stal: Cr³stal 1.0.0
		craftpresence: CraftPresence 2.0.7
		creativecore: CreativeCore 2.10.24
			net_minecraftforge_eventbus: eventbus 6.0.3
		customsplashscreen: Custom Splash Screen 2.1.1
		dashloader: DashLoader 5.0.0-beta.1+1.20.0
			com_github_luben_zstd-jni: zstd-jni 1.5.2-2
			dev_notalpha_taski: Taski 2.1.0
			dev_quantumfusion_hyphen: Hyphen 0.4.0-rc.3
		disableinsecurechattoast: Disable Insecure Chat Toast 1.1.0
		discerning_furnace: Discerning Furnace 1.0.11
		do_a_barrel_roll: Do a Barrel Roll 3.0.1+1.20
			cicada: CICADA 0.4.0
		draggable_lists: Draggable Lists 1.0.0
		durabilityplus: DurabilityPlus 1.0.2
		dynamic-fire-overlay: Dynamic Fire Overlay 1.0.0
		dynamicfps: Dynamic FPS 2.4.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		eatinganimationid: Eating Animation 1.9.4+1.20
		explosiveenhancement: Explosive Enhancement 1.1.0-1.20.x
		extendedclouds: Extended Clouds 1.2.2+1.20
		fabric-api: Fabric API 0.84.0+1.20.1
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.34+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
			fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d177
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.39+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.20+b3afc78b77
			fabric-command-api-v1: Fabric Command API (v1) 1.2.32+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.11+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.49+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.61+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.7+b3afc78b77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.3+b3afc78b77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.1.11+b3afc78b77
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.51+b3afc78b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.21+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.0+b3afc78b77
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.61+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.26+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.7+b3afc78b77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.37+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.41+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.6+b3afc78b77
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.47+b3afc78b77
			fabric-models-v0: Fabric Models (v0) 0.3.35+b3afc78b77
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.8+b3afc78b77
			fabric-networking-v0: Fabric Networking (v0) 0.3.48+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.0.6+b3afc78b77
			fabric-particles-v1: Fabric Particles (v1) 1.0.28+b3afc78b77
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.18+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.6+b3afc78b77
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.1.0+c154966e77
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.4.0+c154966e77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.44+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.33+b3afc78b77
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.26+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.47+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.6+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.6+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.27+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.2.2+b3afc78b77
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.2.0+b3afc78b77
		fabric-language-kotlin: Fabric Language Kotlin 1.9.6+kotlin.1.8.22
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.22
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.22
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.21.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.1
		fabricloader: Fabric Loader 0.14.21
		fabricskyboxes: FabricSkyBoxes 0.7.1+mc1.20
		fallingleaves: Falling Leaves 1.15.1+1.20.1
		fancymenu: FancyMenu 2.14.7
		firstperson: FirstpersonModel 2.2.3
		forgeconfigapiport: Forge Config API Port 7.0.0
		glowing-torchflower: Glowing Torchflower 1.0.0
		harvest: Harvest 1.3.0
		head_in_the_clouds: Head In The Clouds 1.0.0
		helditemtooltips: Held Item Tooltips 7.0.0
		highlight: Highlight unspecified
			resourcefullib: Resourceful Lib 2.0.7
				com_teamresourceful_yabn: yabn 1.0.3
		indium: Indium 1.0.18+mc1.20
		iris: Iris 1.6.4
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		itemswapper: ItemSwapper 0.4.0-mc1.20
		jade: Jade 11.1.3
		java: OpenJDK 64-Bit Server VM 17
		kappa: Kappa 3.0.4
		konkrete: Konkrete 1.6.1
		lithium: Lithium 0.11.2
		loadingscreentips: Loading Screen Tips 1.3.0
		make_bubbles_pop: Make Bubbles Pop Mod 0.1.1-fabric
		memoryleakfix: Memory Leak Fix 1.1.1
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.8
		minecraft: Minecraft 1.20
		mobplaques: Mob Plaques 7.0.0
		modmenu: Mod Menu 7.0.1
		mousetweaks: Mouse Tweaks 2.25
		mousewheelie: Mouse Wheelie 1.11.1+mc1.20-pre2
			amecsapi: Amecs API 1.4.0+mc1.20-pre1
			coat: Coat 1.0.0-beta.20+mc1.20-pre1
			tweed4_annotated: tweed4_annotated 1.3.1+mc1.20-pre1
			tweed4_base: tweed4_base 1.7.1+mc1.20-pre1
			tweed4_data: tweed4_data 1.2.1+mc1.20-pre1
			tweed4_data_hjson: tweed4_data_hjson 1.1.1+mc1.20-pre1
			tweed4_tailor_coat: tweed4_tailor_coat 1.1.3+mc1.20-pre1
			tweed4_tailor_lang_json_descriptions: tweed4_tailor_lang_json_descriptions 1.1.0+mc1.20-pre1
			tweed4_tailor_screen: tweed4_tailor_screen 1.1.4+mc1.20-pre1
		no_more_purple: No More Purple 1.2.1
		norecipebook: NoRecipeBook 2.3+1.20
		notenoughanimations: NotEnoughAnimations 1.6.4
		numeralping: Numeral Ping 1.2.1
		particlerain: Particle Rain 2.0.5
		physicsmod: Physics Mod 3.0.5
		pickupnotifier: Pick Up Notifier 7.0.0
		presencefootsteps: Presence Footsteps 1.9.0
		puzzleslib: Puzzles Lib 7.0.9
		raised: Raised 1.2.2
		reacharound: Reacharound 1.1.2
		reeses-sodium-options: Reese's Sodium Options 1.5.1+mc1.20-build.74
		resourcify: Resourcify 1.1.0
			elementa: Elementa 590+markdown
			universalcraft: UniversalCraft 269
		ridehud: Ride Hud 1.2.3+1.20
		roughlyenoughitems: Roughly Enough Items 12.0.625
			error_notifier: Error Notifier 1.0.9
		sbet: Subjectively Better Enchantment Tooltips 1.0.1
		screenshot_viewer: Screenshot Viewer 1.1.6-fabric-mc1.20.1
			catconfig-mc: Cat Config MC 0.1.1
				io_github_lgatodu47_catconfig: catconfig 0.2.4
		searchables: Searchables 1.0.2
		sfcr: SuperFancyClouds: Rearchitected 1.7.4-mc1.20
		shulkerboxtooltip: Shulker Box Tooltip 4.0.3+1.20
		simplehudenhanced: Simple Hud Enhanced v3.0.0
		skinlayers: 3d Skin Layers 1.5.3-mc1.20
		skinshuffle: SkinShuffle 0.2.1+1.20
			com_konghq_unirest-java_standalone: unirest-java 3.11.9
			commons-validator_commons-validator: commons-validator 1.7
			org_jsoup_jsoup: jsoup 1.16.1
			spruceui: SpruceUI 5.0.0+1.20
			yet_another_config_lib_v3: YetAnotherConfigLib 3.0.1+1.20
				com_twelvemonkeys_common_common-image: common-image 3.9.4
				com_twelvemonkeys_common_common-io: common-io 3.9.4
				com_twelvemonkeys_common_common-lang: common-lang 3.9.4
				com_twelvemonkeys_imageio_imageio-core: imageio-core 3.9.4
				com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.9.4
				com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.9.4
		sodium: Sodium 0.4.10+build.27
		sodium-extra: Sodium Extra 0.4.20+mc1.20-build.103
			caffeineconfig: CaffeineConfig 1.1.0+1.17
		spark: spark 1.10.42
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		spritearrows: Sprite Arrows 1.0.3
		spyglass_astronomy: Spyglass Astronomy 1.0.5-mc1.20+
		stack-to-nearby-chests: Stack to Nearby Chests 0.3.1
			libgui: LibGui 8.0.0+1.20
				jankson: Jankson 5.0.1+j1.2.2
					blue_endless_jankson: jankson 1.2.2
				libninepatch: LibNinePatch 1.2.0
		starlight: Starlight 1.1.2+fabric.dbc156f
		straightenup: Straighten Up 1.2.0
		stylisheffects: Stylish Effects 7.0.0
		swingthrough: SwingThrough ${version}
		third_person_maps: Third Person Maps 1.5.1
		tooltiprareness: Tooltip Rareness 1.0.9
		toomanyplayers: Too Many Players 1.20-1.1.4
		translucent-glass: Translucent Glass 0.1.0
		vanillaconfig: Vanilla Config 1.2.7+1.20
		visuality: Visuality 0.7.0+1.20
		waveycapes: WaveyCapes 1.3.2
		waxednotwaxed: Waxed Not Waxed 1.2.0
		widertab: WiderTab 1.0.0+1.20+
		xaerominimap: Xaero's Minimap 23.5.0
		xaeroworldmap: Xaero's World Map 1.30.6
		youwereslain: You Were Slain 1.0.0-1.20.x
		zoomify: Zoomify 2.10.0
			com_akuleshov7_ktoml-core-jvm: ktoml-core-jvm 0.4.1
			dev_isxander_settxi_settxi-core: settxi-core 2.10.6
			dev_isxander_settxi_settxi-kotlinx-serialization: settxi-kotlinx-serialization 2.10.6
	Loaded Shaderpack: (off)
	NEC status: No NEC detected
	Launched Version: 1.20
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 1080 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 531.79, NVIDIA Corporation
	Window size: 2560x1440
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric, file/Twemojis in MInecraft 1.2.1.zip, minecraft:supporteatinganimation, file/better_flame_particles-v1.0-mc1.20-resourcepack.zip, file/enchant icons 1.20 v1.3.zip, file/corality-1-0-2.zip, file/falling-sakura-1-1-0.zip, file/repottery-v1-3-1.zip, file/EBE_1.20.x_v1.1.zip, continuity:default, minecraft:highlight_extended, translucent-glass:translucent-glass, itemswapper:default, file/Default-Dark-Mode-1.20-2023.6.0.zip, file/Fabulous+Foliage.zip
	Current Language: en_us
	CPU: 24x AMD Ryzen 9 3900XT 12-Core Processor `

**Comment by justliliandev** [comment]
I don't get this error with only these 3 mods present, but I was able to fix a different incompat with etf, can you try version 
1.0.4?

**Comment by wiktormalyska** [comment]
works with 1.0.4
