### ISSUE TITLE
Proposal: API for Registering Custom Arrow Types

### ISSUE THREAD

**Issue by SigmundGranaas** [agnor99/arrow-sprites#6]
Hi @agnor99,

I found the mod extremely useful while developing the dynamic Bow and arrow system in my mod, Forgero. During integration, I've found it necessary to directly implement some parts of your code due to some minor incompatibilities in the load order in the 1.19.2 branch, which is where I am currently developing, but it seems like you fixed this in the recent 1.20 branch.

Ideally I would like to rely on your mod for rendering my arrows as sprites, but that's not possible on my end right now. I think an API to allow custom arrow types registration would be beneficial, making it easier for other mods to interface with yours.

Here's an implementation proposal:

```
public class ArrowSpritesAPI {
    private static final Set<EntityType<? extends AbstractArrow>> customArrows = new HashSet<>();

    public static void registerCustomArrowType(EntityType<? extends AbstractArrow> entityType) {
        customArrows.add(entityType);
    }
    
    public static Set<EntityType<? extends AbstractArrow>> getCustomArrows() {
        return customArrows;
    }
}
```

Which could be used here:
```
public static void replace() {
    Minecraft instance = Minecraft.getInstance();
    List<EntityType<?>> replaceable = new ArrayList<>();
    EntityRendererProvider.Context ctx = new EntityRendererProvider.Context(instance.getEntityRenderDispatcher(), instance.getItemRenderer(), instance.getBlockRenderer(), null, instance.getResourceManager(), new EntityModelSet(), instance.font);
    for (var entry : EntityRenderers.PROVIDERS.entrySet()) {
        try {
            if (entry.getKey() == EntityType.TRIDENT || entry.getValue().create(ctx) instanceof ArrowRenderer<?> || ArrowSpritesAPI.getCustomArrows().contains(entry.getKey())) {
                replaceable.add(entry.getKey());
            }
        } catch (Exception | NoClassDefFoundError ignored) {
        }
    }
    for (EntityType type: replaceable) {
        EntityRenderers.PROVIDERS.put(type, provide());
    }
}

```
Which can be used by me like so:
```
ArrowSpritesAPI.registerCustomArrowType(MyModEntities.MY_CUSTOM_ARROW);

```

Great mod btw! This is just a suggestion, so if you had other plans for an API, go ahead!

**Comment by justliliandev** [comment]
thanks for enjoying this mod. However, this wouldn't work, as, in 1.19.2 this code could have run if my mod runs first. With 1.20 this code wouldn't do anything, as I greedily replace all entity renderers that are some form of arrows, so this wouldn't make sense. I want to change the load order thing for fabric for 1.19 too, but didn't get to it yet

**Comment by justliliandev** [comment]
and to replace arrows, that don't use arrow renderers, I would much rather have a fabric client tag and on forge config option

**Comment by SigmundGranaas** [comment]
> thanks for enjoying this mod. However, this wouldn't work, as, in 1.19.2 this code could have run if my mod runs first. With 1.20 this code wouldn't do anything, as I greedily replace all entity renderers that are some form of arrows, so this wouldn't make sense. I want to change the load order thing for fabric for 1.19 too, but didn't get to it yet

Alright, sounds good!
